<?php 
require_once '../include.php';
checkLogined();
$act=$_REQUEST['act'];
$id=$_REQUEST['id'];
if($act=="logout"){
	logout();
}elseif($act=="addAdmin"){
	$mes=addAdmin();
}elseif($act=="editAdmin"){
	$mes=editAdmin($id);
}elseif($act=="delAdmin"){
	$mes=delAdmin($id);
}elseif($act=="addCate"){
	$mes=addCate();
}elseif($act=="editCate"){
	$where="id={$id}";
	$mes=editCate($where);
}elseif($act=="delCate"){
	$mes=delCate($id);
}elseif($act=="addLab"){
	$mes=addLab();
}elseif($act=="editLab"){
	$where="id={$id}";
	$mes=editLab($where);
}elseif($act=="delLab"){
	$mes=delLab($id);
}elseif($act=="addRole"){
	$mes=addRole();
}elseif($act=="editRole"){
	$where="id={$id}";
	$mes=editRole($where);
}elseif($act=="delRole"){
	$mes=delRole($id);
}elseif($act=="addDev"){
	$mes=addDev();
}elseif($act=="editDev"){
	$mes=editDev($id);
}elseif($act=="delDev"){
	$mes=delDev($id);
}elseif($act=="addRecord"){
	$mes=addRecord();
}elseif($act=="editRecord"){
	$mes=editRecord($id);
}elseif($act=="delRecord"){
	$mes=delRecord($id);
}elseif($act=="addUser"){
	$mes=addUser();
}elseif($act=="delUser"){
		$mes=delUser($id);
}elseif($act=="editUser"){
	$mes=editUser($id);	
}elseif($act=="waterText"){
	$mes=doWaterText($id);
}elseif($act=="waterPic"){
	$mes=doWaterPic($id);
}
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Insert title here</title>
</head>
<body>
<?php 
	if($mes){
		echo $mes;
	}
?>
</body>
</html>